### ISSUE TITLE
Variable binding in vis template not working

### ISSUE THREAD

**Issue by Stefan592** [ioBroker/ioBroker.example#93]
Hi,

I am trying to create a Vis widget based on the Vis template [(https://github.com/ioBroker/ioBroker.example/tree/master/VIS).](https://github.com/ioBroker/ioBroker.example/tree/master/VIS)
Unfortunately I have problems with the variable binding in my repo. In the editor the current value of the variable is read from, but then in the runtime it is not updated.

To exclude problems on my part I have moved the Vis template into a repo [(https://github.com/Stefan592/test)](https://github.com/Stefan592/test) and installed it unchanged in the admin.
The variable update does not work there either. 

Where is the error? 

![image](https://user-images.githubusercontent.com/14180760/157827504-0fa02efe-ed0e-48c9-b7b9-1a25ed97780d.png)
![image](https://user-images.githubusercontent.com/14180760/157827760-da4bef12-91ea-4d7c-b357-a27bf773ff8d.png)

**Comment by Apollon77** [comment]
Please better ask this in Forum/Discord or the vis adapter ...
