### ISSUE TITLE
Is there a way to get the list of supported languages by ioBroker?

### ISSUE THREAD

**Issue by agross** [ioBroker/ioBroker.example#95]
I want to display a dropdown for language selection in an adapter, preferably with the same options that can be set in System settings | System language (the wrench icon in the admin header). Is there an API to get the list of languages?

**Comment by Apollon77** [comment]
No, this list is kond of static right now. and basically these https://github.com/ioBroker/ioBroker.example/blob/master/JavaScript/io-package.json#L7-L16

No plans right now to enhance that

**Comment by agross** [comment]
Thank you!
